with vector_package; use vector_package;
with Ada.Integer_Text_IO, Ada.Text_IO, Ada.Float_Text_IO, Text_IO; 
use Ada.Integer_Text_IO, Ada.Text_IO, Ada.Float_Text_IO, Text_IO;

procedure main is
    V: Vector (100);
    A: Vector (100);
    C: TArray := (6,7,8,9,10);
    D: Vector (100);
begin
    insert (V,11);
    insert (V,12);
    insert(V,13);
    insert(V,14);
    insert(V,15);
    print_Vector(V);
    New_Line;
    Put_Line("Size: " & Integer'Image(Size(V)));
    Put_Line("First: " & Integer'Image(first(V)));
    Put_Line("Last: " & Integer'Image(last(V)));
    Put_Line("Assign 5 4 times:");
    assign(V,4,5);
    print_Vector(V);
    New_Line;
    Put_Line("Pop: ");
    pop(V);
    print_Vector(V);
    New_Line;
    Put_Line("Remove 5: ");
    remove(V,5,true);
    print_Vector(V);
    New_Line;
    insert (A,1);
    insert (A,2);
    insert(A,3);
    insert(A,4);
    insert(A,5);
    Put_Line("Swap: ");
    print_Vector(V);
    New_Line;
    print_Vector(A);
    New_Line;
    swap(V,A);
    print_Vector(V);
    New_Line;
    print_Vector(A);
    New_Line;
    Put_Line("Join A to V: ");
    join(V,A);
    print_Vector(V);
    New_Line;
    Put_Line("Compare V to V: " & Boolean'Image(compare(A,A)));
    Put_Line("Copy Array to V: ");
    copy(V,C);
    print_Vector(V);
    New_Line;
    Put_Line("Clear V: ");
    clear(V);
    print_Vector(V);

    insert (D,13);
    insert (D,16);
    insert(D,14);
    insert(D,12);
    print_Vector(A);
    New_Line;
    print_Vector(D);
    Put_Line("Compare A to D: " & Boolean'Image(compare(A,D)));
end main;